### PR TITLE
fix(api-backup): update response

### PR DESCRIPTION
**Pull request by emeric-martineau**
MR linked : https://github.com/Scalingo/developers-documentation/pull/277

- [x] Add a [changelog entry](https://changelog.scalingo.com/)

### CODE REVIEW

**Review by EtienneM — DISMISSED** [review]
:tada:

**Review by EtienneM — APPROVED** [review]

**Comment by EtienneM** [comment]
Closed in favor of #311 due to CI configuration issue.

**Comment by EtienneM** [comment]
@emeric-martineau Do you have a need for these fields soon or can we delay a go-scalingo release?

**Comment by emeric-martineau** [comment]
@EtienneM you can delay a go-scalingo release

**Pull request closed without merging**
