### PR TITLE
feat(scm_repo_link): add ManualDeployResponse

### PR DESCRIPTION
**Pull request by gnuletik**
Fixes https://github.com/Scalingo/go-scalingo/issues/331

- [x] Add a [changelog entry](https://changelog.scalingo.com/)

### CODE REVIEW

**Comment by Soulou** [comment]
This PR only adds information and is not breaking what to expect from the client, I would only bump a minor if you'd agree @EtienneM

**Review by EtienneM — APPROVED** [review]
Manually executed the tests and linter

```
 emichon@biniou  ~/Documents/Scalingo/golang/src/github.com/Scalingo/go-scalingo   gnuletik/master  grc go test -race -p=1 -count=1 ./...
ok      github.com/Scalingo/go-scalingo/v6      0.076s
?       github.com/Scalingo/go-scalingo/v6/billing      [no test files]
?       github.com/Scalingo/go-scalingo/v6/cmd/gen_events_boilerplate   [no test files]
?       github.com/Scalingo/go-scalingo/v6/cmd/gen_events_specialize    [no test files]
?       github.com/Scalingo/go-scalingo/v6/debug        [no test files]
?       github.com/Scalingo/go-scalingo/v6/examples/app_show    [no test files]
?       github.com/Scalingo/go-scalingo/v6/examples/backup_download     [no test files]
ok      github.com/Scalingo/go-scalingo/v6/http 0.024s
?       github.com/Scalingo/go-scalingo/v6/http/httpmock        [no test files]
?       github.com/Scalingo/go-scalingo/v6/http/tokensservicemock       [no test files]
?       github.com/Scalingo/go-scalingo/v6/io   [no test files]
?       github.com/Scalingo/go-scalingo/v6/scalingomock [no test files]
?       github.com/Scalingo/go-scalingo/v6/test [no test files]
 emichon@biniou  ~/Documents/Scalingo/golang/src/github.com/Scalingo/go-scalingo   gnuletik/master  sc-golangci-lint --modules-download-mode=mod --new-from-rev=$(git ls-remote origin master | cut -f1)
 emichon@biniou  ~/Documents/Scalingo/golang/src/github.com/Scalingo/go-scalingo   gnuletik/master  
```

**Comment by EtienneM** [comment]
@gnuletik thanks for your contribution. It has been released in 6.5.0 (https://github.com/Scalingo/go-scalingo/releases/tag/v6.5.0). You may want to update your CLI PR with this release.

**Comment by gnuletik** [comment]
Awesome ! Thanks for the fast merge 🚀
I'll rebase https://github.com/Scalingo/cli/pull/936

**Pull request merged**
