### PR TITLE
Fix retrocompatibility with static token Client

### PR DESCRIPTION
**Pull request by Soulou**

### CODE REVIEW

**Comment by johnsudaar** [comment]
Just why :/ We released a new version for that reason. Why should we maintain legacy features ?

**Comment by Soulou** [comment]
Because some projects are broken and need last data structures... ie github-integration

**Comment by johnsudaar** [comment]
Then they should be updated or use the v1 branches.

**Comment by Soulou** [comment]
but the v1 branch doesn't have the good structs, do we want to maintain 1.x ans 2.x?

**Comment by johnsudaar** [comment]
No, we want to update the github-integration repo

**Comment by Soulou** [comment]
no time now.. its the whole paradigm which has to be changed, so I prefered to do that as the impact is low

**Pull request merged**
