### PR TITLE
feat(logs): add timestamp to the logs URL

### PR DESCRIPTION
**Pull request by EtienneM**
- [x] Add a [changelog entry](https://changelog.scalingo.com/)

### CODE REVIEW

**Review by Soulou — COMMENTED** [review]
Is it required to work with the new system (aka are current CLI broken?)

**Comment by EtienneM** [comment]
> Is it required to work with the new system (aka are current CLI broken?)

Yep. Current CLI are not broken yet because we didn't released yet everything in prod, but they will if we don't release a new version of the CLI before the release of the logs service.

**Comment by Soulou** [comment]
@EtienneM Is it merged in staging (since it works there currently with my current CLI)

**Review by Soulou — COMMENTED** [review]
See above comment

**Comment by EtienneM** [comment]
> @EtienneM Is it merged in staging (since it works there currently with my current CLI)

Not yet as you will need this PR to be merged in staging first: https://github.com/Scalingo/api/pull/2043

But I wanted to first release the CLI so that I don't break the CLI in staging. But if you prefer, we can first merge the API PR then work on the CLI.

**Review by Soulou — APPROVED** [review]

**Pull request merged**
