### PR TITLE
Add ability to pass dst_app_name to story for same-region migration

### PR DESCRIPTION
**Pull request by Soulou**

### CODE REVIEW

**Comment by johnsudaar** [comment]
Do we really want those kind of things in production. This is useful in dev, but should we present this to end users?

**Comment by Soulou** [comment]
What's the risk adding this?

**Comment by johnsudaar** [comment]
I don't think there's a risk. But i'm not sure there's a point neither.

**Comment by johnsudaar** [comment]
My question isn't could we but should we.

**Comment by Soulou** [comment]
I think, being able to give the destination name can be useful, it's not necessary, but it's not dangerous and an optional feature WHICH is useful in dev

**Comment by Soulou** [comment]
It's just that today we need it for faster dev

**Pull request merged**
