### PR TITLE
review(285) Create mock for DatabasesService, document file and normalize naming

### PR DESCRIPTION
**Pull request by Soulou**
Related to #285 review

- [x] Add a [changelog entry](https://changelog.scalingo.com/)

### CODE REVIEW

**Review by EtienneM — APPROVED** [review]
Thanks a lot for the comments addition

**Comment by Soulou** [comment]
@EtienneM I've changed my vim config to navigate easily into the lint warnings, I'll try to systematically respond to them

**Comment by EtienneM** [comment]
> @EtienneM I've changed my vim config to navigate easily into the lint warnings, I'll try to systematically respond to them

The lint warnings with golangci-lint and our configuration?

**Comment by Soulou** [comment]
Haha not currently it's with `ale` so not bound to our configuration, probably stricter, I've to dig to know how to merge with ours

**Pull request merged**
